server:
  port: 8081

spring:
  application:
    name: dtn-compliance-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:dtn_compliance}
    username: ${DB_USER:dtn_user}
    password: ${DB_PASSWORD:dtn_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Actuator ohne problematische Health Checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    mail:
      enabled: false  # Disable mail health check

# Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

# Logging
logging:
  level:
    com.dtn.compliance: INFO
    org.springframework.web: WARN

---
# Docker Profile
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-compliance}:${DB_PORT:5432}/${DB_NAME:dtn_compliance}
    username: ${DB_USER:dtn_user}
    password: ${DB_PASSWORD:dtn_password}
